### Rota para listar produtos
GET http://localhost:3000/

Content-Type: application/json

### 

### Rota para cadastrar produtos
POST http://localhost:3000/
Content-Type: application/json 

{
    "id": "1",
    "nome": "Monitor 24",
    "preco": 150012312,
    "quantidade": 1312313
}
###

### Editar produtos
PUT http://localhost:3000/1  
Content-Type: application/json

{
    "novoNome": "Monitor 43",
    "novoPreco": 132323,
    "novaQuantidade": 14
}
###

### Deletar produtos
DELETE http://localhost:3000/1
Content-Type: application/json

###
